### PR TITLE
New Disk

### PR DESCRIPTION
**Pull request by ImSimplidius**
Ok just re write the file ( change it to the new one)

### CODE REVIEW

**Comment by ImSimplidius** [comment]
Dont accept the toror file i kinda messed that up

**Comment by xxAROX** [comment]
just reupload the file and commit, then its fixed

**Comment by ImSimplidius** [comment]
Done

**Comment by xxAROX** [comment]
merge?

**Comment by xxAROX** [comment]
merge!

**Comment by xxAROX** [comment]
Perfect!

**Pull request merged**
